SAMPLE_AAX_FILE_PATH = "src/tests/The_Gathering_Storm_Interview_with_the_Narrators-LC_64_22050_stereo.aax"
SAMPLE_AAXC_FILE_PATH = "src/tests/The_Gathering_Storm_Interview_with_the_Narrators-AAX_22_64.aaxc"
SAMPLE_VOUCHER_FILE_PATH = "src/tests/The_Gathering_Storm_Interview_with_the_Narrators-AAX_22_64.voucher"
SAMPLE_TITLE = "The Gathering Storm Interview with the Narrators"
SAMPLE_SIMPLE_TITLE = "The Shorter Storm"
SAMPLE_TITLE_WITH_SERIES = "Brotherhood of the Wolf The Runelords, Book Two"
SAMPLE_LIBRARY = """asin	title	subtitle	authors	narrators	series_title	series_sequence	genres	runtime_length_min	is_finished	percent_complete	rating	num_ratings	date_added	release_date	cover_url	extended_product_description
B0036HZUZ4	The Gathering Storm	Interview with the Narrators	Kate Reading, Michael Kramer	Laura Wilson			Science Fiction & Fantasy, Fantasy, Epic	11	False	0.0	4.2	638	2010-09-26T03:12:54.000Z	2008-12-28	https://m.media-amazon.com/images/I/61Q6sBH786L._SL500_.jpg	Narrators Kate Reading and Michael Kramer have read the audio edition for every book in Robert's Jordan's epic Wheel of Time series. In this interview with Macmillan Audio Director of Production Laura Wilson, they talk about their work on <i>The Gathering Storm</i>, the latest installment of the series, co-written by <i>Mistborn</i> author Brandon Sanderson.
B0036HZUZ4	The Shorter Storm		Kate Reading, Michael Kramer	Laura Wilson			Science Fiction & Fantasy, Fantasy, Epic	11	False	0.0	4.2	638	2010-09-26T03:12:54.000Z	2008-12-28	https://m.media-amazon.com/images/I/61Q6sBH786L._SL500_.jpg	Narrators Kate Reading and Michael Kramer have read the audio edition for every book in Robert's Jordan's epic Wheel of Time series. In this interview with Macmillan Audio Director of Production Laura Wilson, they talk about their work on <i>The Gathering Storm</i>, the latest installment of the series, co-written by <i>Mistborn</i> author Brandon Sanderson.
B0040ME3TS	Wizardborn	The Runelords, Book Three	David Farland	Ray Porter	Runelords	3	Science Fiction & Fantasy, Fantasy, Action & Adventure, Science Fiction & Fantasy, Fantasy, Epic	1154	False	0.0	4.5	1575	2021-09-04T20:19:55.000Z	2010-08-24	https://m.media-amazon.com/images/I/618rrOSO04L._SL500_.jpg	Wizardborn continues the story of the struggle of Gaborn, now the Earth King, who has lost his powers but continues to lead his people. He must contend with the threat of the huge, inhuman Reavers, whose myriads Gaborn and his forces must now pursue across the nation. It has become Gaborn's fate to follow, even into the depths. <p>Raj Ahten, the great warlord endowed with the strength and qualities of thousands of men, once the primary threat to Gaborn, now struggles to retain his own empire.</p>
B002V5B86C	Brotherhood of the Wolf	The Runelords, Book Two	David Farland	Ray Porter	Runelords	2	Science Fiction & Fantasy, Fantasy, Action & Adventure, Science Fiction & Fantasy, Fantasy, Epic	1360	False	10.66	4.5	2034	2021-09-04T20:19:49.000Z	2009-02-06	https://m.media-amazon.com/images/I/61MoTN+EDfL._SL500_.jpg	Raj Ahten, ruler of Indhopal, has used enough forcibles to transform himself into the ultimate warrior: the Sum of All Men. Ahten seeks to bring all of humanity under his rule, destroying any one in his path. But young Prince Gaborn has fulfilled a 2000-year-old prophecy and become the Earth King, a mythic figure who can unleash the forces of the Earth itself. He has managed to drive off Raj Ahten, but Ahten is far from defeated."""

SAMPLE_BOOK = {'asin': 'B0036HZUZ4', 'title': 'The Gathering Storm', 'subtitle': 'Interview with the Narrators', 'extended_product_description': "Narrators Kate Reading and Michael Kramer have read the audio edition for every book in Robert's Jordan's epic Wheel of Time series. In this interview with Macmillan Audio Director of Production Laura Wilson, they talk about their work on <i>The Gathering Storm</i>, the latest installment of the series, co-written by <i>Mistborn</i> author Brandon Sanderson.",
               'authors': 'Kate Reading, Michael Kramer', 'narrators': 'Laura Wilson', 'series_title': '', 'series_sequence': '', 'genres': 'Science Fiction & Fantasy, Fantasy, Epic', 'runtime_length_min': '11', 'is_finished': 'False', 'percent_complete': '0.0', 'rating': '4.2', 'num_ratings': '638', 'date_added': '2010-09-26T03:12:54.000Z', 'release_date': '2008-12-28', 'cover_url': 'https://m.media-amazon.com/images/I/61Q6sBH786L._SL500_.jpg'}
SAMPLE_BOOK_TITLE = 'The Gathering Storm: Interview with the Narrators'

SAMPLE_SIMPLE_BOOK = {'asin': 'not a real ASIN', 'title': 'The Shorter Storm', 'subtitle': '', 'extended_product_description': "Narrators Kate Reading and Michael Kramer have read the audio edition for every book in Robert's Jordan's epic Wheel of Time series. In this interview with Macmillan Audio Director of Production Laura Wilson, they talk about their work on <i>The Gathering Storm</i>, the latest installment of the series, co-written by <i>Mistborn</i> author Brandon Sanderson.",
                      'authors': 'Kate Reading, Michael Kramer', 'narrators': 'Laura Wilson', 'series_title': '', 'series_sequence': '', 'genres': 'Science Fiction & Fantasy, Fantasy, Epic', 'runtime_length_min': '11', 'is_finished': 'False', 'percent_complete': '0.0', 'rating': '4.2', 'num_ratings': '638', 'date_added': '2010-09-26T03:12:54.000Z', 'release_date': '2008-12-28', 'cover_url': 'https://m.media-amazon.com/images/I/61Q6sBH786L._SL500_.jpg'}
SAMPLE_SIMPLE_BOOK_TITLE = 'The Shorter Storm'


SAMPLE_VOUCHER_TEXT = '{ "content_license": { "access_expiry_date": "2024-12-31T12:00:00Z", "acr": "CR!SQXVE6VRA11QHBXA844GBRB6N8RZ", "allowed_users": [ "amzn1.account.AEA5M6RIQTRPKVUBJBS4BO4PIFWA" ], "asin": "B002V5B86C", "drm_type": "Adrm", "license_id": "beafd049-a1c5-43bd-9af2-cf2537f9d39a", "license_response": { "key": "32ac3ec788fb7c391c1a5a5f9b91a604", "iv": "5c66658e54c88d1b6c16591b891adbd9", "refreshDate": "2022-08-17T00:36:13Z", "removalOnExpirationDate": "2022-09-26T00:36:13Z", "rules": [ { "parameters": [ { "expireDate": "2022-08-27T00:36:13Z", "type": "EXPIRES" } ], "name": "DefaultExpiresRule" }, { "parameters": [ { "directedIds": [ "amzn1.account.AEA5M6RIQTRPKVUBJBS4BO4PIFWA" ], "type": "DIRECTED_IDS" } ], "name": "AllowedUsersRule" } ] }, "message": "Customer [ARCM6F233RFGK] has rights to asin [B002V5B86C] for AYCL", "refresh_date": "2022-08-17T00:36:13Z", "removal_date": "2022-09-26T00:36:13Z", "request_id": "9f60048d-2cf1-4a8d-b027-ae325e5ed14c_3CQBY95R14XFJCWB401N", "requires_ad_supported_playback": False, "status_code": "Granted", "voucher_id": "cdn:9f60048d-2cf1-4a8d-b027-ae325e5ed14c_3CQBY95R14XFJCWB401N" }, "response_groups": [ "always-returned", "last_position_heard", "pdf_url", "content_reference" ] }'
