__author__ = "snowskeleton"
__author_email__ = "isaac@snowskeleton.net"
__description__ = "Decrypt AAX and AAXC into M4A"
__license__ = "Apache 2.0"
__status__ = "Development"
__title__ = "snowcrypt"
__url__ = "https://github.com/snowskeleton/snowcrypt"
__version__ = "0.1.1-1"
